version: '3'

services:
  recipe-app:
      build: .
      image: recipe-app
      ports:
        - '3000:3000'
      volumes:
        - .:/usr/src/recipe-app
        - rcp_node_modules:/usr/src/recipe-app/node_modules
      networks:
        - node-network

networks:
  node-network:
    driver: bridge

volumes:
  rcp_node_modules: