version: '3'

services:
  recipe-app:
      build: .
      image: recipe-app
      ports:
        - '3000:3000'
      depends_on:
        - mongodb-primary
      volumes:
        - .:/usr/src/recipe-app
      networks:
        - node-network

networks:
  node-network:
    driver: bridge